x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://loki:3100/loki/api/v1/push"
services:
  grafana:
    image: grafana/grafana:10.0.3
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./config/grafana-datasources.yml
        target: /etc/grafana/provisioning/datasources/datasources.yml
      - grafana-data:/var/lib/grafana
    environment:
      - 'GF_DEFAULT_APP_MODE=production'
      - 'GF_LOG_LEVEL=debug'
      - 'GF_SMTP_ENABLED=true'
      - 'GF_SMTP_HOST=firstdeliverygroup-com.mail.protection.outlook.com:25'
      - 'GF_SMTP_FROM_ADDRESS=grafana@firstdeliverygroup.com'
      - 'GF_SERVER_ROOT_URL=https://monitoring.first-admin.com'
    networks:
      - tun_prod
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  loki:
    image: grafana/loki:2.8.4
    ports:
      - target: 3100
        published: 3100
        protocol: tcp
        mode: host
    volumes:
      - loki-data:/loki
      - type: bind
        source: ./config/loki-config.yml
        target: /etc/loki/local-config.yml
    command: -config.file=/etc/loki/local-config.yml
    networks:
      - tun_prod
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  promtail:
    image: grafana/promtail:2.8.4
    volumes:
      - type: bind
        source: ./config/docker-config.yml
        target: /etc/promtail/docker-config.yml
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yml
    depends_on:
      - loki
    networks:
      - tun_prod
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
  
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - prom_data:/prometheus
      - type: bind
        source: ./config/prometheus.yml
        target: /etc/prometheus/prometheus.yml
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    networks:
      - tun_prod
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - tun_prod
    deploy:
      mode: global
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  cadvisor:
    image: google/cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - tun_prod
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s


volumes:
  loki-data:
    driver: local
  grafana-data:
    driver: local
  prom_data:
    driver: local

configs:
  prometheus_config:
    file: ./config/prometheus.yml

networks:
  tun_prod:
    external: true