version: '3.9'

services:
  grafana:
    image: grafana/grafana:10.0.3
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./grafana-datasources.yml
        target: /etc/grafana/provisioning/datasources/datasources.yml
      - grafana-data:/var/lib/grafana
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_LOG_LEVEL=debug
    networks:
      - graf-net

  loki:
    image: grafana/loki:2.8.4
    ports:
      - target: 3100
        published: 3100
        protocol: tcp
        mode: host
    volumes:
      - loki-data:/loki
      - type: bind
        source: ./loki-config.yml
        target: /etc/loki/local-config.yml
    command: -config.file=/etc/loki/local-config.yml
    networks:
      - graf-net

  promtail:
    image:  grafana/promtail:2.8.4
    volumes:
      - type: bind
        source: ./docker-config.yml
        target: /etc/promtail/docker-config.yml
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yml
    depends_on:
      - loki
    networks:
      - graf-net
      
volumes:
  loki-data:
  grafana-data:

networks:
  graf-net:
